spring.application.name=springintro

spring.datasource.url=jdbc:mysql://localhost:3306/springintro?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret-key=VGhpcy1pcy1hLXNob3djYXNlLXNlY3JldC1rZXktZm9yLXNwcmluZ2ludHJvLTIwMjY=
# 15 min in ms
jwt.expiration=900000
jwt.cookie-name=jwt-cookie
# 15 days in ms
jwt.refresh-token.expiration=1296000000
jwt.refresh-token.cookie-name=refresh-jwt-cookie